CREATE DATABASE ExampleDB;
GO 
ALTER DATABASE ExampleDB 
ADD FILEGROUP TestFileGroup1;
ALTER DATABASE ExampleDB 
ADD FILEGROUP TestFileGroup2;
GO 
ALTER DATABASE ExampleDB 
ADD FILE (NAME = TestFile1, FILENAME = 'D:\MSSQL\TestFile1.ndf', SIZE = 5MB) TO FILEGROUP TestFileGroup1;
ALTER DATABASE ExampleDB ADD FILE (NAME = TestFile2,FILENAME = 'D:\MSSQL\TestFile2.ndf',SIZE = 5MB)TO FILEGROUP TestFileGroup2;
GO 
CREATE TABLE ExampleDB..t1 (c1 INT) ON TestFileGroup1;
CREATE TABLE ExampleDB..t2 (c1 INT) ON TestFileGroup2;
GO
INSERT INTO ExampleDB..t1 VALUES (1);
INSERT INTO ExampleDB..t2 VALUES (2);
GO 
BACKUP DATABASE ExampleDB TO DISK = 'D:\MSSQL\ExampleDB.bck';
GO
--Restore Primary FileGroup WITH PARTIAL
RESTORE DATABASE ExampleDB	FILEGROUP = 'primary' FROM DISK = 'D:\MSSQL\ExampleDB.bck' WITH PARTIAL, NORECOVERY;
GO
RESTORE DATABASE ExampleDB	FILEGROUP = 'TestFileGroup1' FROM DISK = 'D:\MSSQL\ExampleDB.bck' WITH NORECOVERY;
GO