/****************************************************/
/* Created by: SQL Server 2012  Profiler          */
/* Date: 05/07/2014  03:07:00 PM         */
/****************************************************/


-- Create a Queue
declare @rc int
declare @TraceID int
declare @maxfilesize bigint
set @maxfilesize = 5 

-- Please replace the text InsertFileNameHere, with an appropriate
-- filename prefixed by a path, e.g., c:\MyFolder\MyTrace. The .trc extension
-- will be appended to the filename automatically. If you are writing from
-- remote server to local drive, please use UNC path and make sure server has
-- write access to your network share

exec @rc = sp_trace_create @TraceID output, 0, N'InsertFileNameHere', @maxfilesize, NULL 
if (@rc != 0) goto error

-- Client side File and Table cannot be scripted

-- Set the events
declare @on bit
set @on = 1
exec sp_trace_setevent @TraceID, 74, 3, @on
exec sp_trace_setevent @TraceID, 74, 11, @on
exec sp_trace_setevent @TraceID, 74, 4, @on
exec sp_trace_setevent @TraceID, 74, 12, @on
exec sp_trace_setevent @TraceID, 74, 6, @on
exec sp_trace_setevent @TraceID, 74, 7, @on
exec sp_trace_setevent @TraceID, 74, 8, @on
exec sp_trace_setevent @TraceID, 74, 9, @on
exec sp_trace_setevent @TraceID, 74, 10, @on
exec sp_trace_setevent @TraceID, 74, 14, @on
exec sp_trace_setevent @TraceID, 74, 25, @on
exec sp_trace_setevent @TraceID, 74, 26, @on
exec sp_trace_setevent @TraceID, 74, 35, @on
exec sp_trace_setevent @TraceID, 74, 41, @on
exec sp_trace_setevent @TraceID, 74, 49, @on
exec sp_trace_setevent @TraceID, 74, 50, @on
exec sp_trace_setevent @TraceID, 74, 51, @on
exec sp_trace_setevent @TraceID, 74, 60, @on
exec sp_trace_setevent @TraceID, 74, 64, @on
exec sp_trace_setevent @TraceID, 74, 66, @on
exec sp_trace_setevent @TraceID, 53, 3, @on
exec sp_trace_setevent @TraceID, 53, 11, @on
exec sp_trace_setevent @TraceID, 53, 4, @on
exec sp_trace_setevent @TraceID, 53, 12, @on
exec sp_trace_setevent @TraceID, 53, 6, @on
exec sp_trace_setevent @TraceID, 53, 7, @on
exec sp_trace_setevent @TraceID, 53, 8, @on
exec sp_trace_setevent @TraceID, 53, 9, @on
exec sp_trace_setevent @TraceID, 53, 10, @on
exec sp_trace_setevent @TraceID, 53, 14, @on
exec sp_trace_setevent @TraceID, 53, 25, @on
exec sp_trace_setevent @TraceID, 53, 26, @on
exec sp_trace_setevent @TraceID, 53, 35, @on
exec sp_trace_setevent @TraceID, 53, 41, @on
exec sp_trace_setevent @TraceID, 53, 49, @on
exec sp_trace_setevent @TraceID, 53, 50, @on
exec sp_trace_setevent @TraceID, 53, 51, @on
exec sp_trace_setevent @TraceID, 53, 60, @on
exec sp_trace_setevent @TraceID, 53, 64, @on
exec sp_trace_setevent @TraceID, 53, 66, @on
exec sp_trace_setevent @TraceID, 70, 3, @on
exec sp_trace_setevent @TraceID, 70, 11, @on
exec sp_trace_setevent @TraceID, 70, 4, @on
exec sp_trace_setevent @TraceID, 70, 12, @on
exec sp_trace_setevent @TraceID, 70, 6, @on
exec sp_trace_setevent @TraceID, 70, 7, @on
exec sp_trace_setevent @TraceID, 70, 8, @on
exec sp_trace_setevent @TraceID, 70, 9, @on
exec sp_trace_setevent @TraceID, 70, 10, @on
exec sp_trace_setevent @TraceID, 70, 14, @on
exec sp_trace_setevent @TraceID, 70, 26, @on
exec sp_trace_setevent @TraceID, 70, 35, @on
exec sp_trace_setevent @TraceID, 70, 41, @on
exec sp_trace_setevent @TraceID, 70, 49, @on
exec sp_trace_setevent @TraceID, 70, 50, @on
exec sp_trace_setevent @TraceID, 70, 51, @on
exec sp_trace_setevent @TraceID, 70, 60, @on
exec sp_trace_setevent @TraceID, 70, 64, @on
exec sp_trace_setevent @TraceID, 70, 66, @on
exec sp_trace_setevent @TraceID, 112, 1, @on
exec sp_trace_setevent @TraceID, 112, 9, @on
exec sp_trace_setevent @TraceID, 112, 3, @on
exec sp_trace_setevent @TraceID, 112, 11, @on
exec sp_trace_setevent @TraceID, 112, 4, @on
exec sp_trace_setevent @TraceID, 112, 6, @on
exec sp_trace_setevent @TraceID, 112, 7, @on
exec sp_trace_setevent @TraceID, 112, 8, @on
exec sp_trace_setevent @TraceID, 112, 10, @on
exec sp_trace_setevent @TraceID, 112, 12, @on
exec sp_trace_setevent @TraceID, 112, 14, @on
exec sp_trace_setevent @TraceID, 112, 23, @on
exec sp_trace_setevent @TraceID, 112, 26, @on
exec sp_trace_setevent @TraceID, 112, 28, @on
exec sp_trace_setevent @TraceID, 112, 29, @on
exec sp_trace_setevent @TraceID, 112, 34, @on
exec sp_trace_setevent @TraceID, 112, 35, @on
exec sp_trace_setevent @TraceID, 112, 37, @on
exec sp_trace_setevent @TraceID, 112, 38, @on
exec sp_trace_setevent @TraceID, 112, 40, @on
exec sp_trace_setevent @TraceID, 112, 41, @on
exec sp_trace_setevent @TraceID, 112, 49, @on
exec sp_trace_setevent @TraceID, 112, 50, @on
exec sp_trace_setevent @TraceID, 112, 51, @on
exec sp_trace_setevent @TraceID, 112, 60, @on
exec sp_trace_setevent @TraceID, 112, 64, @on
exec sp_trace_setevent @TraceID, 128, 1, @on
exec sp_trace_setevent @TraceID, 128, 3, @on
exec sp_trace_setevent @TraceID, 128, 11, @on
exec sp_trace_setevent @TraceID, 128, 4, @on
exec sp_trace_setevent @TraceID, 128, 12, @on
exec sp_trace_setevent @TraceID, 128, 6, @on
exec sp_trace_setevent @TraceID, 128, 7, @on
exec sp_trace_setevent @TraceID, 128, 8, @on
exec sp_trace_setevent @TraceID, 128, 10, @on
exec sp_trace_setevent @TraceID, 128, 14, @on
exec sp_trace_setevent @TraceID, 128, 21, @on
exec sp_trace_setevent @TraceID, 128, 23, @on
exec sp_trace_setevent @TraceID, 128, 26, @on
exec sp_trace_setevent @TraceID, 128, 28, @on
exec sp_trace_setevent @TraceID, 128, 29, @on
exec sp_trace_setevent @TraceID, 128, 34, @on
exec sp_trace_setevent @TraceID, 128, 35, @on
exec sp_trace_setevent @TraceID, 128, 37, @on
exec sp_trace_setevent @TraceID, 128, 40, @on
exec sp_trace_setevent @TraceID, 128, 41, @on
exec sp_trace_setevent @TraceID, 128, 49, @on
exec sp_trace_setevent @TraceID, 128, 50, @on
exec sp_trace_setevent @TraceID, 128, 51, @on
exec sp_trace_setevent @TraceID, 128, 60, @on
exec sp_trace_setevent @TraceID, 128, 64, @on
exec sp_trace_setevent @TraceID, 172, 1, @on
exec sp_trace_setevent @TraceID, 172, 9, @on
exec sp_trace_setevent @TraceID, 172, 2, @on
exec sp_trace_setevent @TraceID, 172, 10, @on
exec sp_trace_setevent @TraceID, 172, 3, @on
exec sp_trace_setevent @TraceID, 172, 4, @on
exec sp_trace_setevent @TraceID, 172, 6, @on
exec sp_trace_setevent @TraceID, 172, 7, @on
exec sp_trace_setevent @TraceID, 172, 8, @on
exec sp_trace_setevent @TraceID, 172, 11, @on
exec sp_trace_setevent @TraceID, 172, 12, @on
exec sp_trace_setevent @TraceID, 172, 14, @on
exec sp_trace_setevent @TraceID, 172, 19, @on
exec sp_trace_setevent @TraceID, 172, 21, @on
exec sp_trace_setevent @TraceID, 172, 23, @on
exec sp_trace_setevent @TraceID, 172, 26, @on
exec sp_trace_setevent @TraceID, 172, 28, @on
exec sp_trace_setevent @TraceID, 172, 29, @on
exec sp_trace_setevent @TraceID, 172, 34, @on
exec sp_trace_setevent @TraceID, 172, 35, @on
exec sp_trace_setevent @TraceID, 172, 37, @on
exec sp_trace_setevent @TraceID, 172, 39, @on
exec sp_trace_setevent @TraceID, 172, 40, @on
exec sp_trace_setevent @TraceID, 172, 41, @on
exec sp_trace_setevent @TraceID, 172, 42, @on
exec sp_trace_setevent @TraceID, 172, 43, @on
exec sp_trace_setevent @TraceID, 172, 49, @on
exec sp_trace_setevent @TraceID, 172, 50, @on
exec sp_trace_setevent @TraceID, 172, 51, @on
exec sp_trace_setevent @TraceID, 172, 60, @on
exec sp_trace_setevent @TraceID, 172, 64, @on
exec sp_trace_setevent @TraceID, 129, 1, @on
exec sp_trace_setevent @TraceID, 129, 3, @on
exec sp_trace_setevent @TraceID, 129, 11, @on
exec sp_trace_setevent @TraceID, 129, 4, @on
exec sp_trace_setevent @TraceID, 129, 5, @on
exec sp_trace_setevent @TraceID, 129, 6, @on
exec sp_trace_setevent @TraceID, 129, 7, @on
exec sp_trace_setevent @TraceID, 129, 8, @on
exec sp_trace_setevent @TraceID, 129, 10, @on
exec sp_trace_setevent @TraceID, 129, 12, @on
exec sp_trace_setevent @TraceID, 129, 14, @on
exec sp_trace_setevent @TraceID, 129, 21, @on
exec sp_trace_setevent @TraceID, 129, 23, @on
exec sp_trace_setevent @TraceID, 129, 26, @on
exec sp_trace_setevent @TraceID, 129, 28, @on
exec sp_trace_setevent @TraceID, 129, 29, @on
exec sp_trace_setevent @TraceID, 129, 34, @on
exec sp_trace_setevent @TraceID, 129, 35, @on
exec sp_trace_setevent @TraceID, 129, 37, @on
exec sp_trace_setevent @TraceID, 129, 40, @on
exec sp_trace_setevent @TraceID, 129, 41, @on
exec sp_trace_setevent @TraceID, 129, 49, @on
exec sp_trace_setevent @TraceID, 129, 50, @on
exec sp_trace_setevent @TraceID, 129, 51, @on
exec sp_trace_setevent @TraceID, 129, 60, @on
exec sp_trace_setevent @TraceID, 129, 64, @on
exec sp_trace_setevent @TraceID, 135, 1, @on
exec sp_trace_setevent @TraceID, 135, 3, @on
exec sp_trace_setevent @TraceID, 135, 11, @on
exec sp_trace_setevent @TraceID, 135, 4, @on
exec sp_trace_setevent @TraceID, 135, 12, @on
exec sp_trace_setevent @TraceID, 135, 6, @on
exec sp_trace_setevent @TraceID, 135, 7, @on
exec sp_trace_setevent @TraceID, 135, 8, @on
exec sp_trace_setevent @TraceID, 135, 10, @on
exec sp_trace_setevent @TraceID, 135, 14, @on
exec sp_trace_setevent @TraceID, 135, 23, @on
exec sp_trace_setevent @TraceID, 135, 26, @on
exec sp_trace_setevent @TraceID, 135, 28, @on
exec sp_trace_setevent @TraceID, 135, 29, @on
exec sp_trace_setevent @TraceID, 135, 34, @on
exec sp_trace_setevent @TraceID, 135, 35, @on
exec sp_trace_setevent @TraceID, 135, 37, @on
exec sp_trace_setevent @TraceID, 135, 39, @on
exec sp_trace_setevent @TraceID, 135, 40, @on
exec sp_trace_setevent @TraceID, 135, 41, @on
exec sp_trace_setevent @TraceID, 135, 49, @on
exec sp_trace_setevent @TraceID, 135, 50, @on
exec sp_trace_setevent @TraceID, 135, 51, @on
exec sp_trace_setevent @TraceID, 135, 60, @on
exec sp_trace_setevent @TraceID, 135, 64, @on
exec sp_trace_setevent @TraceID, 178, 1, @on
exec sp_trace_setevent @TraceID, 178, 3, @on
exec sp_trace_setevent @TraceID, 178, 11, @on
exec sp_trace_setevent @TraceID, 178, 4, @on
exec sp_trace_setevent @TraceID, 178, 12, @on
exec sp_trace_setevent @TraceID, 178, 6, @on
exec sp_trace_setevent @TraceID, 178, 7, @on
exec sp_trace_setevent @TraceID, 178, 8, @on
exec sp_trace_setevent @TraceID, 178, 10, @on
exec sp_trace_setevent @TraceID, 178, 14, @on
exec sp_trace_setevent @TraceID, 178, 21, @on
exec sp_trace_setevent @TraceID, 178, 23, @on
exec sp_trace_setevent @TraceID, 178, 26, @on
exec sp_trace_setevent @TraceID, 178, 28, @on
exec sp_trace_setevent @TraceID, 178, 29, @on
exec sp_trace_setevent @TraceID, 178, 34, @on
exec sp_trace_setevent @TraceID, 178, 35, @on
exec sp_trace_setevent @TraceID, 178, 37, @on
exec sp_trace_setevent @TraceID, 178, 40, @on
exec sp_trace_setevent @TraceID, 178, 41, @on
exec sp_trace_setevent @TraceID, 178, 49, @on
exec sp_trace_setevent @TraceID, 178, 50, @on
exec sp_trace_setevent @TraceID, 178, 51, @on
exec sp_trace_setevent @TraceID, 178, 60, @on
exec sp_trace_setevent @TraceID, 178, 64, @on
exec sp_trace_setevent @TraceID, 133, 1, @on
exec sp_trace_setevent @TraceID, 133, 2, @on
exec sp_trace_setevent @TraceID, 133, 10, @on
exec sp_trace_setevent @TraceID, 133, 3, @on
exec sp_trace_setevent @TraceID, 133, 11, @on
exec sp_trace_setevent @TraceID, 133, 4, @on
exec sp_trace_setevent @TraceID, 133, 6, @on
exec sp_trace_setevent @TraceID, 133, 7, @on
exec sp_trace_setevent @TraceID, 133, 8, @on
exec sp_trace_setevent @TraceID, 133, 12, @on
exec sp_trace_setevent @TraceID, 133, 14, @on
exec sp_trace_setevent @TraceID, 133, 19, @on
exec sp_trace_setevent @TraceID, 133, 21, @on
exec sp_trace_setevent @TraceID, 133, 23, @on
exec sp_trace_setevent @TraceID, 133, 26, @on
exec sp_trace_setevent @TraceID, 133, 28, @on
exec sp_trace_setevent @TraceID, 133, 29, @on
exec sp_trace_setevent @TraceID, 133, 34, @on
exec sp_trace_setevent @TraceID, 133, 35, @on
exec sp_trace_setevent @TraceID, 133, 37, @on
exec sp_trace_setevent @TraceID, 133, 38, @on
exec sp_trace_setevent @TraceID, 133, 40, @on
exec sp_trace_setevent @TraceID, 133, 41, @on
exec sp_trace_setevent @TraceID, 133, 49, @on
exec sp_trace_setevent @TraceID, 133, 50, @on
exec sp_trace_setevent @TraceID, 133, 51, @on
exec sp_trace_setevent @TraceID, 133, 60, @on
exec sp_trace_setevent @TraceID, 133, 64, @on
exec sp_trace_setevent @TraceID, 130, 1, @on
exec sp_trace_setevent @TraceID, 130, 3, @on
exec sp_trace_setevent @TraceID, 130, 11, @on
exec sp_trace_setevent @TraceID, 130, 4, @on
exec sp_trace_setevent @TraceID, 130, 12, @on
exec sp_trace_setevent @TraceID, 130, 6, @on
exec sp_trace_setevent @TraceID, 130, 7, @on
exec sp_trace_setevent @TraceID, 130, 8, @on
exec sp_trace_setevent @TraceID, 130, 10, @on
exec sp_trace_setevent @TraceID, 130, 14, @on
exec sp_trace_setevent @TraceID, 130, 21, @on
exec sp_trace_setevent @TraceID, 130, 23, @on
exec sp_trace_setevent @TraceID, 130, 26, @on
exec sp_trace_setevent @TraceID, 130, 28, @on
exec sp_trace_setevent @TraceID, 130, 29, @on
exec sp_trace_setevent @TraceID, 130, 34, @on
exec sp_trace_setevent @TraceID, 130, 35, @on
exec sp_trace_setevent @TraceID, 130, 37, @on
exec sp_trace_setevent @TraceID, 130, 39, @on
exec sp_trace_setevent @TraceID, 130, 40, @on
exec sp_trace_setevent @TraceID, 130, 41, @on
exec sp_trace_setevent @TraceID, 130, 42, @on
exec sp_trace_setevent @TraceID, 130, 43, @on
exec sp_trace_setevent @TraceID, 130, 49, @on
exec sp_trace_setevent @TraceID, 130, 50, @on
exec sp_trace_setevent @TraceID, 130, 51, @on
exec sp_trace_setevent @TraceID, 130, 60, @on
exec sp_trace_setevent @TraceID, 130, 64, @on
exec sp_trace_setevent @TraceID, 14, 1, @on
exec sp_trace_setevent @TraceID, 14, 9, @on
exec sp_trace_setevent @TraceID, 14, 2, @on
exec sp_trace_setevent @TraceID, 14, 66, @on
exec sp_trace_setevent @TraceID, 14, 10, @on
exec sp_trace_setevent @TraceID, 14, 3, @on
exec sp_trace_setevent @TraceID, 14, 11, @on
exec sp_trace_setevent @TraceID, 14, 6, @on
exec sp_trace_setevent @TraceID, 14, 7, @on
exec sp_trace_setevent @TraceID, 14, 8, @on
exec sp_trace_setevent @TraceID, 14, 12, @on
exec sp_trace_setevent @TraceID, 14, 14, @on
exec sp_trace_setevent @TraceID, 14, 21, @on
exec sp_trace_setevent @TraceID, 14, 23, @on
exec sp_trace_setevent @TraceID, 14, 25, @on
exec sp_trace_setevent @TraceID, 14, 26, @on
exec sp_trace_setevent @TraceID, 14, 35, @on
exec sp_trace_setevent @TraceID, 14, 41, @on
exec sp_trace_setevent @TraceID, 14, 49, @on
exec sp_trace_setevent @TraceID, 14, 51, @on
exec sp_trace_setevent @TraceID, 14, 57, @on
exec sp_trace_setevent @TraceID, 14, 60, @on
exec sp_trace_setevent @TraceID, 14, 64, @on
exec sp_trace_setevent @TraceID, 107, 1, @on
exec sp_trace_setevent @TraceID, 107, 9, @on
exec sp_trace_setevent @TraceID, 107, 3, @on
exec sp_trace_setevent @TraceID, 107, 11, @on
exec sp_trace_setevent @TraceID, 107, 4, @on
exec sp_trace_setevent @TraceID, 107, 6, @on
exec sp_trace_setevent @TraceID, 107, 7, @on
exec sp_trace_setevent @TraceID, 107, 8, @on
exec sp_trace_setevent @TraceID, 107, 10, @on
exec sp_trace_setevent @TraceID, 107, 12, @on
exec sp_trace_setevent @TraceID, 107, 14, @on
exec sp_trace_setevent @TraceID, 107, 21, @on
exec sp_trace_setevent @TraceID, 107, 23, @on
exec sp_trace_setevent @TraceID, 107, 26, @on
exec sp_trace_setevent @TraceID, 107, 28, @on
exec sp_trace_setevent @TraceID, 107, 29, @on
exec sp_trace_setevent @TraceID, 107, 34, @on
exec sp_trace_setevent @TraceID, 107, 35, @on
exec sp_trace_setevent @TraceID, 107, 37, @on
exec sp_trace_setevent @TraceID, 107, 40, @on
exec sp_trace_setevent @TraceID, 107, 41, @on
exec sp_trace_setevent @TraceID, 107, 42, @on
exec sp_trace_setevent @TraceID, 107, 43, @on
exec sp_trace_setevent @TraceID, 107, 49, @on
exec sp_trace_setevent @TraceID, 107, 50, @on
exec sp_trace_setevent @TraceID, 107, 51, @on
exec sp_trace_setevent @TraceID, 107, 60, @on
exec sp_trace_setevent @TraceID, 107, 64, @on
exec sp_trace_setevent @TraceID, 15, 3, @on
exec sp_trace_setevent @TraceID, 15, 11, @on
exec sp_trace_setevent @TraceID, 15, 6, @on
exec sp_trace_setevent @TraceID, 15, 7, @on
exec sp_trace_setevent @TraceID, 15, 8, @on
exec sp_trace_setevent @TraceID, 15, 9, @on
exec sp_trace_setevent @TraceID, 15, 10, @on
exec sp_trace_setevent @TraceID, 15, 12, @on
exec sp_trace_setevent @TraceID, 15, 13, @on
exec sp_trace_setevent @TraceID, 15, 14, @on
exec sp_trace_setevent @TraceID, 15, 15, @on
exec sp_trace_setevent @TraceID, 15, 16, @on
exec sp_trace_setevent @TraceID, 15, 17, @on
exec sp_trace_setevent @TraceID, 15, 18, @on
exec sp_trace_setevent @TraceID, 15, 21, @on
exec sp_trace_setevent @TraceID, 15, 23, @on
exec sp_trace_setevent @TraceID, 15, 26, @on
exec sp_trace_setevent @TraceID, 15, 35, @on
exec sp_trace_setevent @TraceID, 15, 41, @on
exec sp_trace_setevent @TraceID, 15, 49, @on
exec sp_trace_setevent @TraceID, 15, 51, @on
exec sp_trace_setevent @TraceID, 15, 57, @on
exec sp_trace_setevent @TraceID, 15, 60, @on
exec sp_trace_setevent @TraceID, 15, 64, @on
exec sp_trace_setevent @TraceID, 15, 66, @on
exec sp_trace_setevent @TraceID, 118, 1, @on
exec sp_trace_setevent @TraceID, 118, 9, @on
exec sp_trace_setevent @TraceID, 118, 3, @on
exec sp_trace_setevent @TraceID, 118, 4, @on
exec sp_trace_setevent @TraceID, 118, 5, @on
exec sp_trace_setevent @TraceID, 118, 6, @on
exec sp_trace_setevent @TraceID, 118, 7, @on
exec sp_trace_setevent @TraceID, 118, 8, @on
exec sp_trace_setevent @TraceID, 118, 10, @on
exec sp_trace_setevent @TraceID, 118, 11, @on
exec sp_trace_setevent @TraceID, 118, 12, @on
exec sp_trace_setevent @TraceID, 118, 14, @on
exec sp_trace_setevent @TraceID, 118, 21, @on
exec sp_trace_setevent @TraceID, 118, 23, @on
exec sp_trace_setevent @TraceID, 118, 26, @on
exec sp_trace_setevent @TraceID, 118, 28, @on
exec sp_trace_setevent @TraceID, 118, 29, @on
exec sp_trace_setevent @TraceID, 118, 34, @on
exec sp_trace_setevent @TraceID, 118, 35, @on
exec sp_trace_setevent @TraceID, 118, 37, @on
exec sp_trace_setevent @TraceID, 118, 40, @on
exec sp_trace_setevent @TraceID, 118, 41, @on
exec sp_trace_setevent @TraceID, 118, 49, @on
exec sp_trace_setevent @TraceID, 118, 50, @on
exec sp_trace_setevent @TraceID, 118, 51, @on
exec sp_trace_setevent @TraceID, 118, 60, @on
exec sp_trace_setevent @TraceID, 118, 64, @on
exec sp_trace_setevent @TraceID, 131, 1, @on
exec sp_trace_setevent @TraceID, 131, 3, @on
exec sp_trace_setevent @TraceID, 131, 11, @on
exec sp_trace_setevent @TraceID, 131, 4, @on
exec sp_trace_setevent @TraceID, 131, 12, @on
exec sp_trace_setevent @TraceID, 131, 6, @on
exec sp_trace_setevent @TraceID, 131, 7, @on
exec sp_trace_setevent @TraceID, 131, 8, @on
exec sp_trace_setevent @TraceID, 131, 10, @on
exec sp_trace_setevent @TraceID, 131, 14, @on
exec sp_trace_setevent @TraceID, 131, 21, @on
exec sp_trace_setevent @TraceID, 131, 23, @on
exec sp_trace_setevent @TraceID, 131, 26, @on
exec sp_trace_setevent @TraceID, 131, 28, @on
exec sp_trace_setevent @TraceID, 131, 29, @on
exec sp_trace_setevent @TraceID, 131, 34, @on
exec sp_trace_setevent @TraceID, 131, 35, @on
exec sp_trace_setevent @TraceID, 131, 37, @on
exec sp_trace_setevent @TraceID, 131, 40, @on
exec sp_trace_setevent @TraceID, 131, 41, @on
exec sp_trace_setevent @TraceID, 131, 49, @on
exec sp_trace_setevent @TraceID, 131, 50, @on
exec sp_trace_setevent @TraceID, 131, 51, @on
exec sp_trace_setevent @TraceID, 131, 59, @on
exec sp_trace_setevent @TraceID, 131, 60, @on
exec sp_trace_setevent @TraceID, 131, 64, @on
exec sp_trace_setevent @TraceID, 171, 1, @on
exec sp_trace_setevent @TraceID, 171, 9, @on
exec sp_trace_setevent @TraceID, 171, 2, @on
exec sp_trace_setevent @TraceID, 171, 10, @on
exec sp_trace_setevent @TraceID, 171, 3, @on
exec sp_trace_setevent @TraceID, 171, 4, @on
exec sp_trace_setevent @TraceID, 171, 6, @on
exec sp_trace_setevent @TraceID, 171, 7, @on
exec sp_trace_setevent @TraceID, 171, 8, @on
exec sp_trace_setevent @TraceID, 171, 11, @on
exec sp_trace_setevent @TraceID, 171, 12, @on
exec sp_trace_setevent @TraceID, 171, 14, @on
exec sp_trace_setevent @TraceID, 171, 19, @on
exec sp_trace_setevent @TraceID, 171, 21, @on
exec sp_trace_setevent @TraceID, 171, 23, @on
exec sp_trace_setevent @TraceID, 171, 26, @on
exec sp_trace_setevent @TraceID, 171, 28, @on
exec sp_trace_setevent @TraceID, 171, 29, @on
exec sp_trace_setevent @TraceID, 171, 34, @on
exec sp_trace_setevent @TraceID, 171, 35, @on
exec sp_trace_setevent @TraceID, 171, 37, @on
exec sp_trace_setevent @TraceID, 171, 40, @on
exec sp_trace_setevent @TraceID, 171, 41, @on
exec sp_trace_setevent @TraceID, 171, 42, @on
exec sp_trace_setevent @TraceID, 171, 43, @on
exec sp_trace_setevent @TraceID, 171, 49, @on
exec sp_trace_setevent @TraceID, 171, 50, @on
exec sp_trace_setevent @TraceID, 171, 51, @on
exec sp_trace_setevent @TraceID, 171, 60, @on
exec sp_trace_setevent @TraceID, 171, 64, @on
exec sp_trace_setevent @TraceID, 176, 1, @on
exec sp_trace_setevent @TraceID, 176, 9, @on
exec sp_trace_setevent @TraceID, 176, 3, @on
exec sp_trace_setevent @TraceID, 176, 11, @on
exec sp_trace_setevent @TraceID, 176, 4, @on
exec sp_trace_setevent @TraceID, 176, 6, @on
exec sp_trace_setevent @TraceID, 176, 7, @on
exec sp_trace_setevent @TraceID, 176, 8, @on
exec sp_trace_setevent @TraceID, 176, 10, @on
exec sp_trace_setevent @TraceID, 176, 12, @on
exec sp_trace_setevent @TraceID, 176, 14, @on
exec sp_trace_setevent @TraceID, 176, 21, @on
exec sp_trace_setevent @TraceID, 176, 23, @on
exec sp_trace_setevent @TraceID, 176, 26, @on
exec sp_trace_setevent @TraceID, 176, 28, @on
exec sp_trace_setevent @TraceID, 176, 29, @on
exec sp_trace_setevent @TraceID, 176, 34, @on
exec sp_trace_setevent @TraceID, 176, 35, @on
exec sp_trace_setevent @TraceID, 176, 37, @on
exec sp_trace_setevent @TraceID, 176, 40, @on
exec sp_trace_setevent @TraceID, 176, 41, @on
exec sp_trace_setevent @TraceID, 176, 45, @on
exec sp_trace_setevent @TraceID, 176, 46, @on
exec sp_trace_setevent @TraceID, 176, 49, @on
exec sp_trace_setevent @TraceID, 176, 50, @on
exec sp_trace_setevent @TraceID, 176, 51, @on
exec sp_trace_setevent @TraceID, 176, 60, @on
exec sp_trace_setevent @TraceID, 176, 64, @on
exec sp_trace_setevent @TraceID, 134, 1, @on
exec sp_trace_setevent @TraceID, 134, 3, @on
exec sp_trace_setevent @TraceID, 134, 11, @on
exec sp_trace_setevent @TraceID, 134, 4, @on
exec sp_trace_setevent @TraceID, 134, 12, @on
exec sp_trace_setevent @TraceID, 134, 6, @on
exec sp_trace_setevent @TraceID, 134, 7, @on
exec sp_trace_setevent @TraceID, 134, 8, @on
exec sp_trace_setevent @TraceID, 134, 10, @on
exec sp_trace_setevent @TraceID, 134, 14, @on
exec sp_trace_setevent @TraceID, 134, 23, @on
exec sp_trace_setevent @TraceID, 134, 26, @on
exec sp_trace_setevent @TraceID, 134, 28, @on
exec sp_trace_setevent @TraceID, 134, 29, @on
exec sp_trace_setevent @TraceID, 134, 34, @on
exec sp_trace_setevent @TraceID, 134, 35, @on
exec sp_trace_setevent @TraceID, 134, 37, @on
exec sp_trace_setevent @TraceID, 134, 39, @on
exec sp_trace_setevent @TraceID, 134, 40, @on
exec sp_trace_setevent @TraceID, 134, 41, @on
exec sp_trace_setevent @TraceID, 134, 42, @on
exec sp_trace_setevent @TraceID, 134, 43, @on
exec sp_trace_setevent @TraceID, 134, 49, @on
exec sp_trace_setevent @TraceID, 134, 50, @on
exec sp_trace_setevent @TraceID, 134, 51, @on
exec sp_trace_setevent @TraceID, 134, 60, @on
exec sp_trace_setevent @TraceID, 134, 64, @on
exec sp_trace_setevent @TraceID, 173, 1, @on
exec sp_trace_setevent @TraceID, 173, 3, @on
exec sp_trace_setevent @TraceID, 173, 11, @on
exec sp_trace_setevent @TraceID, 173, 4, @on
exec sp_trace_setevent @TraceID, 173, 12, @on
exec sp_trace_setevent @TraceID, 173, 6, @on
exec sp_trace_setevent @TraceID, 173, 7, @on
exec sp_trace_setevent @TraceID, 173, 8, @on
exec sp_trace_setevent @TraceID, 173, 10, @on
exec sp_trace_setevent @TraceID, 173, 14, @on
exec sp_trace_setevent @TraceID, 173, 21, @on
exec sp_trace_setevent @TraceID, 173, 23, @on
exec sp_trace_setevent @TraceID, 173, 26, @on
exec sp_trace_setevent @TraceID, 173, 28, @on
exec sp_trace_setevent @TraceID, 173, 29, @on
exec sp_trace_setevent @TraceID, 173, 34, @on
exec sp_trace_setevent @TraceID, 173, 35, @on
exec sp_trace_setevent @TraceID, 173, 37, @on
exec sp_trace_setevent @TraceID, 173, 40, @on
exec sp_trace_setevent @TraceID, 173, 41, @on
exec sp_trace_setevent @TraceID, 173, 49, @on
exec sp_trace_setevent @TraceID, 173, 50, @on
exec sp_trace_setevent @TraceID, 173, 51, @on
exec sp_trace_setevent @TraceID, 173, 60, @on
exec sp_trace_setevent @TraceID, 173, 64, @on
exec sp_trace_setevent @TraceID, 132, 1, @on
exec sp_trace_setevent @TraceID, 132, 2, @on
exec sp_trace_setevent @TraceID, 132, 10, @on
exec sp_trace_setevent @TraceID, 132, 3, @on
exec sp_trace_setevent @TraceID, 132, 11, @on
exec sp_trace_setevent @TraceID, 132, 4, @on
exec sp_trace_setevent @TraceID, 132, 6, @on
exec sp_trace_setevent @TraceID, 132, 7, @on
exec sp_trace_setevent @TraceID, 132, 8, @on
exec sp_trace_setevent @TraceID, 132, 12, @on
exec sp_trace_setevent @TraceID, 132, 14, @on
exec sp_trace_setevent @TraceID, 132, 19, @on
exec sp_trace_setevent @TraceID, 132, 21, @on
exec sp_trace_setevent @TraceID, 132, 23, @on
exec sp_trace_setevent @TraceID, 132, 26, @on
exec sp_trace_setevent @TraceID, 132, 28, @on
exec sp_trace_setevent @TraceID, 132, 29, @on
exec sp_trace_setevent @TraceID, 132, 34, @on
exec sp_trace_setevent @TraceID, 132, 35, @on
exec sp_trace_setevent @TraceID, 132, 37, @on
exec sp_trace_setevent @TraceID, 132, 40, @on
exec sp_trace_setevent @TraceID, 132, 41, @on
exec sp_trace_setevent @TraceID, 132, 49, @on
exec sp_trace_setevent @TraceID, 132, 50, @on
exec sp_trace_setevent @TraceID, 132, 51, @on
exec sp_trace_setevent @TraceID, 132, 60, @on
exec sp_trace_setevent @TraceID, 132, 64, @on
exec sp_trace_setevent @TraceID, 177, 1, @on
exec sp_trace_setevent @TraceID, 177, 9, @on
exec sp_trace_setevent @TraceID, 177, 3, @on
exec sp_trace_setevent @TraceID, 177, 4, @on
exec sp_trace_setevent @TraceID, 177, 5, @on
exec sp_trace_setevent @TraceID, 177, 6, @on
exec sp_trace_setevent @TraceID, 177, 7, @on
exec sp_trace_setevent @TraceID, 177, 8, @on
exec sp_trace_setevent @TraceID, 177, 10, @on
exec sp_trace_setevent @TraceID, 177, 11, @on
exec sp_trace_setevent @TraceID, 177, 12, @on
exec sp_trace_setevent @TraceID, 177, 14, @on
exec sp_trace_setevent @TraceID, 177, 21, @on
exec sp_trace_setevent @TraceID, 177, 23, @on
exec sp_trace_setevent @TraceID, 177, 26, @on
exec sp_trace_setevent @TraceID, 177, 28, @on
exec sp_trace_setevent @TraceID, 177, 29, @on
exec sp_trace_setevent @TraceID, 177, 34, @on
exec sp_trace_setevent @TraceID, 177, 35, @on
exec sp_trace_setevent @TraceID, 177, 37, @on
exec sp_trace_setevent @TraceID, 177, 39, @on
exec sp_trace_setevent @TraceID, 177, 40, @on
exec sp_trace_setevent @TraceID, 177, 41, @on
exec sp_trace_setevent @TraceID, 177, 42, @on
exec sp_trace_setevent @TraceID, 177, 43, @on
exec sp_trace_setevent @TraceID, 177, 45, @on
exec sp_trace_setevent @TraceID, 177, 49, @on
exec sp_trace_setevent @TraceID, 177, 50, @on
exec sp_trace_setevent @TraceID, 177, 51, @on
exec sp_trace_setevent @TraceID, 177, 60, @on
exec sp_trace_setevent @TraceID, 177, 64, @on
exec sp_trace_setevent @TraceID, 170, 1, @on
exec sp_trace_setevent @TraceID, 170, 9, @on
exec sp_trace_setevent @TraceID, 170, 2, @on
exec sp_trace_setevent @TraceID, 170, 10, @on
exec sp_trace_setevent @TraceID, 170, 3, @on
exec sp_trace_setevent @TraceID, 170, 4, @on
exec sp_trace_setevent @TraceID, 170, 6, @on
exec sp_trace_setevent @TraceID, 170, 7, @on
exec sp_trace_setevent @TraceID, 170, 8, @on
exec sp_trace_setevent @TraceID, 170, 11, @on
exec sp_trace_setevent @TraceID, 170, 12, @on
exec sp_trace_setevent @TraceID, 170, 14, @on
exec sp_trace_setevent @TraceID, 170, 19, @on
exec sp_trace_setevent @TraceID, 170, 21, @on
exec sp_trace_setevent @TraceID, 170, 23, @on
exec sp_trace_setevent @TraceID, 170, 26, @on
exec sp_trace_setevent @TraceID, 170, 28, @on
exec sp_trace_setevent @TraceID, 170, 29, @on
exec sp_trace_setevent @TraceID, 170, 34, @on
exec sp_trace_setevent @TraceID, 170, 35, @on
exec sp_trace_setevent @TraceID, 170, 37, @on
exec sp_trace_setevent @TraceID, 170, 40, @on
exec sp_trace_setevent @TraceID, 170, 41, @on
exec sp_trace_setevent @TraceID, 170, 42, @on
exec sp_trace_setevent @TraceID, 170, 43, @on
exec sp_trace_setevent @TraceID, 170, 49, @on
exec sp_trace_setevent @TraceID, 170, 50, @on
exec sp_trace_setevent @TraceID, 170, 51, @on
exec sp_trace_setevent @TraceID, 170, 60, @on
exec sp_trace_setevent @TraceID, 170, 64, @on
exec sp_trace_setevent @TraceID, 113, 1, @on
exec sp_trace_setevent @TraceID, 113, 9, @on
exec sp_trace_setevent @TraceID, 113, 2, @on
exec sp_trace_setevent @TraceID, 113, 3, @on
exec sp_trace_setevent @TraceID, 113, 4, @on
exec sp_trace_setevent @TraceID, 113, 5, @on
exec sp_trace_setevent @TraceID, 113, 6, @on
exec sp_trace_setevent @TraceID, 113, 7, @on
exec sp_trace_setevent @TraceID, 113, 8, @on
exec sp_trace_setevent @TraceID, 113, 10, @on
exec sp_trace_setevent @TraceID, 113, 11, @on
exec sp_trace_setevent @TraceID, 113, 12, @on
exec sp_trace_setevent @TraceID, 113, 14, @on
exec sp_trace_setevent @TraceID, 113, 19, @on
exec sp_trace_setevent @TraceID, 113, 21, @on
exec sp_trace_setevent @TraceID, 113, 23, @on
exec sp_trace_setevent @TraceID, 113, 26, @on
exec sp_trace_setevent @TraceID, 113, 28, @on
exec sp_trace_setevent @TraceID, 113, 29, @on
exec sp_trace_setevent @TraceID, 113, 35, @on
exec sp_trace_setevent @TraceID, 113, 40, @on
exec sp_trace_setevent @TraceID, 113, 41, @on
exec sp_trace_setevent @TraceID, 113, 49, @on
exec sp_trace_setevent @TraceID, 113, 50, @on
exec sp_trace_setevent @TraceID, 113, 51, @on
exec sp_trace_setevent @TraceID, 113, 60, @on
exec sp_trace_setevent @TraceID, 113, 64, @on
exec sp_trace_setevent @TraceID, 17, 1, @on
exec sp_trace_setevent @TraceID, 17, 9, @on
exec sp_trace_setevent @TraceID, 17, 2, @on
exec sp_trace_setevent @TraceID, 17, 66, @on
exec sp_trace_setevent @TraceID, 17, 10, @on
exec sp_trace_setevent @TraceID, 17, 3, @on
exec sp_trace_setevent @TraceID, 17, 11, @on
exec sp_trace_setevent @TraceID, 17, 6, @on
exec sp_trace_setevent @TraceID, 17, 7, @on
exec sp_trace_setevent @TraceID, 17, 8, @on
exec sp_trace_setevent @TraceID, 17, 12, @on
exec sp_trace_setevent @TraceID, 17, 13, @on
exec sp_trace_setevent @TraceID, 17, 14, @on
exec sp_trace_setevent @TraceID, 17, 15, @on
exec sp_trace_setevent @TraceID, 17, 25, @on
exec sp_trace_setevent @TraceID, 17, 26, @on
exec sp_trace_setevent @TraceID, 17, 35, @on
exec sp_trace_setevent @TraceID, 17, 41, @on
exec sp_trace_setevent @TraceID, 17, 49, @on
exec sp_trace_setevent @TraceID, 17, 51, @on
exec sp_trace_setevent @TraceID, 17, 57, @on
exec sp_trace_setevent @TraceID, 17, 60, @on
exec sp_trace_setevent @TraceID, 17, 64, @on
exec sp_trace_setevent @TraceID, 100, 1, @on
exec sp_trace_setevent @TraceID, 100, 9, @on
exec sp_trace_setevent @TraceID, 100, 3, @on
exec sp_trace_setevent @TraceID, 100, 11, @on
exec sp_trace_setevent @TraceID, 100, 4, @on
exec sp_trace_setevent @TraceID, 100, 6, @on
exec sp_trace_setevent @TraceID, 100, 7, @on
exec sp_trace_setevent @TraceID, 100, 8, @on
exec sp_trace_setevent @TraceID, 100, 10, @on
exec sp_trace_setevent @TraceID, 100, 12, @on
exec sp_trace_setevent @TraceID, 100, 14, @on
exec sp_trace_setevent @TraceID, 100, 26, @on
exec sp_trace_setevent @TraceID, 100, 34, @on
exec sp_trace_setevent @TraceID, 100, 35, @on
exec sp_trace_setevent @TraceID, 100, 41, @on
exec sp_trace_setevent @TraceID, 100, 49, @on
exec sp_trace_setevent @TraceID, 100, 50, @on
exec sp_trace_setevent @TraceID, 100, 51, @on
exec sp_trace_setevent @TraceID, 100, 60, @on
exec sp_trace_setevent @TraceID, 100, 64, @on
exec sp_trace_setevent @TraceID, 100, 66, @on
exec sp_trace_setevent @TraceID, 11, 1, @on
exec sp_trace_setevent @TraceID, 11, 9, @on
exec sp_trace_setevent @TraceID, 11, 2, @on
exec sp_trace_setevent @TraceID, 11, 66, @on
exec sp_trace_setevent @TraceID, 11, 10, @on
exec sp_trace_setevent @TraceID, 11, 3, @on
exec sp_trace_setevent @TraceID, 11, 4, @on
exec sp_trace_setevent @TraceID, 11, 6, @on
exec sp_trace_setevent @TraceID, 11, 7, @on
exec sp_trace_setevent @TraceID, 11, 8, @on
exec sp_trace_setevent @TraceID, 11, 11, @on
exec sp_trace_setevent @TraceID, 11, 12, @on
exec sp_trace_setevent @TraceID, 11, 14, @on
exec sp_trace_setevent @TraceID, 11, 25, @on
exec sp_trace_setevent @TraceID, 11, 26, @on
exec sp_trace_setevent @TraceID, 11, 34, @on
exec sp_trace_setevent @TraceID, 11, 35, @on
exec sp_trace_setevent @TraceID, 11, 41, @on
exec sp_trace_setevent @TraceID, 11, 49, @on
exec sp_trace_setevent @TraceID, 11, 50, @on
exec sp_trace_setevent @TraceID, 11, 51, @on
exec sp_trace_setevent @TraceID, 11, 60, @on
exec sp_trace_setevent @TraceID, 11, 64, @on
exec sp_trace_setevent @TraceID, 43, 1, @on
exec sp_trace_setevent @TraceID, 43, 9, @on
exec sp_trace_setevent @TraceID, 43, 2, @on
exec sp_trace_setevent @TraceID, 43, 66, @on
exec sp_trace_setevent @TraceID, 43, 3, @on
exec sp_trace_setevent @TraceID, 43, 4, @on
exec sp_trace_setevent @TraceID, 43, 5, @on
exec sp_trace_setevent @TraceID, 43, 6, @on
exec sp_trace_setevent @TraceID, 43, 7, @on
exec sp_trace_setevent @TraceID, 43, 8, @on
exec sp_trace_setevent @TraceID, 43, 10, @on
exec sp_trace_setevent @TraceID, 43, 11, @on
exec sp_trace_setevent @TraceID, 43, 12, @on
exec sp_trace_setevent @TraceID, 43, 13, @on
exec sp_trace_setevent @TraceID, 43, 14, @on
exec sp_trace_setevent @TraceID, 43, 15, @on
exec sp_trace_setevent @TraceID, 43, 26, @on
exec sp_trace_setevent @TraceID, 43, 28, @on
exec sp_trace_setevent @TraceID, 43, 29, @on
exec sp_trace_setevent @TraceID, 43, 34, @on
exec sp_trace_setevent @TraceID, 43, 35, @on
exec sp_trace_setevent @TraceID, 43, 41, @on
exec sp_trace_setevent @TraceID, 43, 49, @on
exec sp_trace_setevent @TraceID, 43, 50, @on
exec sp_trace_setevent @TraceID, 43, 51, @on
exec sp_trace_setevent @TraceID, 43, 60, @on
exec sp_trace_setevent @TraceID, 43, 64, @on
exec sp_trace_setevent @TraceID, 72, 3, @on
exec sp_trace_setevent @TraceID, 72, 11, @on
exec sp_trace_setevent @TraceID, 72, 4, @on
exec sp_trace_setevent @TraceID, 72, 12, @on
exec sp_trace_setevent @TraceID, 72, 6, @on
exec sp_trace_setevent @TraceID, 72, 7, @on
exec sp_trace_setevent @TraceID, 72, 8, @on
exec sp_trace_setevent @TraceID, 72, 9, @on
exec sp_trace_setevent @TraceID, 72, 10, @on
exec sp_trace_setevent @TraceID, 72, 14, @on
exec sp_trace_setevent @TraceID, 72, 26, @on
exec sp_trace_setevent @TraceID, 72, 35, @on
exec sp_trace_setevent @TraceID, 72, 41, @on
exec sp_trace_setevent @TraceID, 72, 49, @on
exec sp_trace_setevent @TraceID, 72, 50, @on
exec sp_trace_setevent @TraceID, 72, 51, @on
exec sp_trace_setevent @TraceID, 72, 60, @on
exec sp_trace_setevent @TraceID, 72, 64, @on
exec sp_trace_setevent @TraceID, 72, 66, @on
exec sp_trace_setevent @TraceID, 71, 3, @on
exec sp_trace_setevent @TraceID, 71, 11, @on
exec sp_trace_setevent @TraceID, 71, 4, @on
exec sp_trace_setevent @TraceID, 71, 12, @on
exec sp_trace_setevent @TraceID, 71, 6, @on
exec sp_trace_setevent @TraceID, 71, 7, @on
exec sp_trace_setevent @TraceID, 71, 8, @on
exec sp_trace_setevent @TraceID, 71, 9, @on
exec sp_trace_setevent @TraceID, 71, 10, @on
exec sp_trace_setevent @TraceID, 71, 14, @on
exec sp_trace_setevent @TraceID, 71, 26, @on
exec sp_trace_setevent @TraceID, 71, 35, @on
exec sp_trace_setevent @TraceID, 71, 41, @on
exec sp_trace_setevent @TraceID, 71, 49, @on
exec sp_trace_setevent @TraceID, 71, 50, @on
exec sp_trace_setevent @TraceID, 71, 51, @on
exec sp_trace_setevent @TraceID, 71, 60, @on
exec sp_trace_setevent @TraceID, 71, 64, @on
exec sp_trace_setevent @TraceID, 71, 66, @on
exec sp_trace_setevent @TraceID, 12, 1, @on
exec sp_trace_setevent @TraceID, 12, 9, @on
exec sp_trace_setevent @TraceID, 12, 3, @on
exec sp_trace_setevent @TraceID, 12, 11, @on
exec sp_trace_setevent @TraceID, 12, 4, @on
exec sp_trace_setevent @TraceID, 12, 6, @on
exec sp_trace_setevent @TraceID, 12, 7, @on
exec sp_trace_setevent @TraceID, 12, 8, @on
exec sp_trace_setevent @TraceID, 12, 10, @on
exec sp_trace_setevent @TraceID, 12, 12, @on
exec sp_trace_setevent @TraceID, 12, 13, @on
exec sp_trace_setevent @TraceID, 12, 14, @on
exec sp_trace_setevent @TraceID, 12, 15, @on
exec sp_trace_setevent @TraceID, 12, 16, @on
exec sp_trace_setevent @TraceID, 12, 17, @on
exec sp_trace_setevent @TraceID, 12, 18, @on
exec sp_trace_setevent @TraceID, 12, 26, @on
exec sp_trace_setevent @TraceID, 12, 35, @on
exec sp_trace_setevent @TraceID, 12, 41, @on
exec sp_trace_setevent @TraceID, 12, 49, @on
exec sp_trace_setevent @TraceID, 12, 50, @on
exec sp_trace_setevent @TraceID, 12, 51, @on
exec sp_trace_setevent @TraceID, 12, 60, @on
exec sp_trace_setevent @TraceID, 12, 64, @on
exec sp_trace_setevent @TraceID, 12, 66, @on
exec sp_trace_setevent @TraceID, 13, 1, @on
exec sp_trace_setevent @TraceID, 13, 9, @on
exec sp_trace_setevent @TraceID, 13, 3, @on
exec sp_trace_setevent @TraceID, 13, 11, @on
exec sp_trace_setevent @TraceID, 13, 4, @on
exec sp_trace_setevent @TraceID, 13, 6, @on
exec sp_trace_setevent @TraceID, 13, 7, @on
exec sp_trace_setevent @TraceID, 13, 8, @on
exec sp_trace_setevent @TraceID, 13, 10, @on
exec sp_trace_setevent @TraceID, 13, 12, @on
exec sp_trace_setevent @TraceID, 13, 14, @on
exec sp_trace_setevent @TraceID, 13, 26, @on
exec sp_trace_setevent @TraceID, 13, 35, @on
exec sp_trace_setevent @TraceID, 13, 41, @on
exec sp_trace_setevent @TraceID, 13, 49, @on
exec sp_trace_setevent @TraceID, 13, 50, @on
exec sp_trace_setevent @TraceID, 13, 51, @on
exec sp_trace_setevent @TraceID, 13, 60, @on
exec sp_trace_setevent @TraceID, 13, 64, @on
exec sp_trace_setevent @TraceID, 13, 66, @on


-- Set the Filters
declare @intfilter int
declare @bigintfilter bigint

exec sp_trace_setfilter @TraceID, 10, 0, 7, N'SQL Server Profiler - d38c4e9a-bdc1-4f88-a1e2-6c917a834dcd'
-- Set the trace status to start
exec sp_trace_setstatus @TraceID, 1

-- display trace id for future references
select TraceID=@TraceID
goto finish

error: 
select ErrorCode=@rc

finish: 
go
